# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "94db1839edf3824ff838370e82bdc8bf"
name = "whatsapp-chat-extension"
application_url = "https://whatsapp-chat-extension-production.up.railway.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_metaobjects,write_metaobject_definitions"

[auth]
redirect_urls = [ "https://whatsapp-chat-extension-production.up.railway.app/auth/callback" ]

[webhooks]
api_version = "2025-01"

    [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request"]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/redact"]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  compliance_topics = ["shop/redact"]
  uri = "/webhooks/shop/redact"
  
  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[build]
automatically_update_urls_on_dev = true
